version: '3.8'

services:
  agroadmin:
    image: ${DOCKER_REGISTRY-}agroadmin
    build:
      context: .
      dockerfile: AgroAdmin/AgroAdmin/Dockerfile
    container_name: agro_admin_api
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      - Telegram__BotToken=${TELEGRAM_BOT_TOKEN}
      - Telegram__ChatId=${TELEGRAM_CHAT_ID}
      - RabbitMQ__Url=${RABBITMQ_URL}
      - ApiUrl=${API_URL}
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - agro_network
    volumes:
      - ./secrets/oauth-credentials.json:/root/.aspnet/google/oauth-credentials.json
      - ./secrets/token.json:/root/.aspnet/google/token.json
      - agro_keys:/root/.aspnet/DataProtection-Keys
    user: root

  notification_worker:
    image: ${DOCKER_REGISTRY-}agroadmin-worker
    build:
      context: .
      dockerfile: AgroAdmin.NotificationWorker/Dockerfile
    container_name: agro_notification_worker
    env_file: .env
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      - Telegram__BotToken=${TELEGRAM_BOT_TOKEN}
      - Telegram__ChatId=${TELEGRAM_CHAT_ID}
      - RabbitMQ__Url=${RABBITMQ_URL}
    depends_on:
      - rabbitmq
      - db
    networks:
      - agro_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: agro_rabbit_local
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - agro_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agro_mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - agro_mssql_data:/var/opt/mssql
    networks:
      - agro_network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong!Password" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  agro_network:
    driver: bridge

volumes:
  agro_mssql_data:
  agro_keys:
