<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AgroAdmin.NotificationWorker-63d76712-f404-427e-b1f4-62babed11662</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.4" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.16.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgroAdmin.Domain\AgroAdmin.Domain.csproj" />
    <ProjectReference Include="..\AgroAdmin.Infrastructure\AgroAdmin.Infrastructure.csproj" />
    <ProjectReference Include="..\AgroAdmin.Shared\AgroAdmin.Shared.csproj" />
  </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.json">
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </Content>
        <Content Update="appsettings.Development.json">
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </Content>
    </ItemGroup>


</Project>
