name: Build, publish and deploy to MonsterASP.NET

on:
  workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Install dependencies
        run: dotnet restore AgroAdmin/AgroAdmin/AgroAdmin.csproj
        
      - name: Build
        run: dotnet build AgroAdmin/AgroAdmin/AgroAdmin.csproj --configuration Release --no-restore

      - name: Publish
        # Собираем всё в папку ./publish-folder для деплоя
        run: dotnet publish AgroAdmin/AgroAdmin/AgroAdmin.csproj --configuration Release --output ./publish-folder --runtime win-x86 --no-self-contained
        
      - name: Deploy to MonsterASP.NET
        # Используем твой рабочий XML профиль из секрета
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish-folder
          clean: true # Попытка автоматической очистки wwwroot
